name: Generate PDF

on:
  push:
    branches:
      - main # Change this to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install puppeteer

      - name: Generate PDF
        run: |
          npx puppeteer print README.md --pdf ./assets/README.pdf
