name: Generate PDF from Readme

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up pandoc
      run: sudo apt-get install -y pandoc

    - name: Generate PDF
      run: pandoc README.md -o assets/README.pdf
