name: Convert README.md to PDF

on:
  push:

jobs:
  convert-readme-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: ./pdfs
          build_pdf: true
